"""Instrument registry seed.

Source of truth for the metadata sidecar over Yahoo symbols. Every distinct
symbol in `entity_tickers` plus the brief's mover set lives here.

To re-seed: `uv run python -m src.instruments.seed`. The script is idempotent
(INSERT OR REPLACE on `symbol`) and only touches the `instruments` table.

Adding a new instrument: append a dict to `INSTRUMENTS` and re-run.
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path
from typing import Any

DB_PATH = Path(__file__).resolve().parents[2] / "db" / "hf.db"


# Each entry is a dict; keys mirror the `instruments` schema columns.
# Required: symbol, display, short, asset_class.
# Optional: aliases, canonical_symbol, alpaca_symbol, fmp_symbol,
# tradable (default 1), proxy_for, active (default 1).
# `canonical_symbol` lets non-Yahoo input strings (e.g. `USDJPY`, `DXY`, `BTC`)
# point at the canonical Yahoo row; the resolver short-circuits through it
# so callers never need to call Mesh `resolve_symbol` for known aliases.
INSTRUMENTS: list[dict[str, Any]] = [
    # ── Equity indices (Yahoo `^` prefix; non-tradable concepts) ──────────
    {"symbol": "^GSPC", "display": "S&P 500 Index", "short": "S&P 500",
     "asset_class": "equity_index", "tradable": 0,
     "aliases": ["S&P 500", "S&P", "SPX", "SP 500", "S&P500"]},
    {"symbol": "^IXIC", "display": "Nasdaq Composite", "short": "Nasdaq",
     "asset_class": "equity_index", "tradable": 0,
     "aliases": ["Nasdaq Composite", "Nasdaq", "IXIC"]},
    {"symbol": "^DJI", "display": "Dow Jones Industrial Average", "short": "Dow",
     "asset_class": "equity_index", "tradable": 0,
     "aliases": ["Dow Jones", "Dow", "DJIA", "Dow Industrials"]},
    {"symbol": "^BSESN", "display": "BSE Sensex", "short": "Sensex",
     "asset_class": "equity_index", "tradable": 0,
     "aliases": ["BSE Sensex", "Sensex", "BSE 30"]},
    {"symbol": "^NSEI", "display": "NIFTY 50", "short": "Nifty 50",
     "asset_class": "equity_index", "tradable": 0,
     "aliases": ["NIFTY 50", "Nifty 50", "Nifty"]},
    {"symbol": "^VIX", "display": "VIX", "short": "VIX",
     "asset_class": "vol", "tradable": 0,
     "aliases": ["VIX", "Volatility Index", "Fear Gauge"]},

    # ── Rates ─────────────────────────────────────────────────────────────
    {"symbol": "^TNX", "display": "10-Year US Treasury Yield", "short": "10Y UST",
     "asset_class": "rate", "tradable": 0,
     "aliases": ["10-year", "10Y", "10Y Treasury", "TNX", "10-year Treasury",
                 "10-year yield", "10y note"]},

    # ── FX (Yahoo `=X` form) ──────────────────────────────────────────────
    {"symbol": "DX-Y.NYB", "display": "US Dollar Index", "short": "DXY",
     "asset_class": "fx", "tradable": 0,
     "aliases": ["US Dollar Index", "Dollar Index", "DXY"],
     "fmp_symbol": "DXY"},
    {"symbol": "DXY", "display": "US Dollar Index", "short": "DXY",
     "asset_class": "fx", "tradable": 0,
     "aliases": ["DXY", "US Dollar Index", "Dollar Index"],
     "canonical_symbol": "DX-Y.NYB"},
    {"symbol": "JPY=X", "display": "USD/JPY", "short": "USD/JPY",
     "asset_class": "fx",
     "aliases": ["USD/JPY", "USDJPY", "Yen", "Japanese Yen"],
     "fmp_symbol": "USDJPY"},
    {"symbol": "USDJPY", "display": "USD/JPY", "short": "USD/JPY",
     "asset_class": "fx",
     "aliases": ["USDJPY", "USD/JPY"],
     "canonical_symbol": "JPY=X"},
    {"symbol": "EURUSD=X", "display": "EUR/USD", "short": "EUR/USD",
     "asset_class": "fx",
     "aliases": ["EUR/USD", "EURUSD", "Euro"],
     "fmp_symbol": "EURUSD"},

    # ── Commodities (Yahoo `=F` futures) ──────────────────────────────────
    {"symbol": "BZ=F", "display": "Brent Crude", "short": "Brent",
     "asset_class": "commodity",
     "aliases": ["Brent", "Brent Crude", "Brent oil"],
     "fmp_symbol": "BZUSD"},
    {"symbol": "CL=F", "display": "WTI Crude", "short": "WTI",
     "asset_class": "commodity",
     "aliases": ["WTI", "WTI Crude", "Crude Oil", "WTI oil"],
     "fmp_symbol": "CLUSD"},
    {"symbol": "GC=F", "display": "Gold", "short": "Gold",
     "asset_class": "commodity",
     "aliases": ["Gold", "Gold futures", "spot gold"],
     "fmp_symbol": "GCUSD"},
    {"symbol": "NG=F", "display": "Natural Gas", "short": "Nat Gas",
     "asset_class": "commodity",
     "aliases": ["Natural Gas", "Nat Gas", "natgas"],
     "fmp_symbol": "NGUSD"},

    # ── Index / commodity proxy ETFs ──────────────────────────────────────
    {"symbol": "SPY", "display": "S&P 500 (SPY)", "short": "S&P 500",
     "asset_class": "etf", "proxy_for": "^GSPC",
     "aliases": ["SPY", "S&P 500 ETF"]},
    {"symbol": "QQQ", "display": "Nasdaq 100 (QQQ)", "short": "Nasdaq 100",
     "asset_class": "etf",
     "aliases": ["QQQ", "Nasdaq 100", "NDX"]},
    {"symbol": "GLD", "display": "SPDR Gold Trust (GLD)", "short": "GLD",
     "asset_class": "etf", "proxy_for": "GC=F",
     "aliases": ["GLD", "Gold ETF"]},
    {"symbol": "USO", "display": "United States Oil Fund (USO)", "short": "USO",
     "asset_class": "etf", "proxy_for": "CL=F",
     "aliases": ["USO", "Oil ETF"]},
    {"symbol": "UNG", "display": "United States Natural Gas Fund (UNG)",
     "short": "UNG", "asset_class": "etf", "proxy_for": "NG=F",
     "aliases": ["UNG", "Natural Gas ETF"]},
    {"symbol": "DBA", "display": "Invesco DB Agriculture Fund (DBA)",
     "short": "DBA", "asset_class": "etf",
     "aliases": ["DBA", "Agriculture ETF"]},
    {"symbol": "TLT", "display": "iShares 20+ Year Treasury Bond ETF (TLT)",
     "short": "TLT", "asset_class": "etf", "proxy_for": "^TNX",
     "aliases": ["TLT", "Long Treasury ETF"]},
    {"symbol": "TMV", "display": "Direxion 20Y Treasury Bear 3X (TMV)",
     "short": "TMV", "asset_class": "etf", "proxy_for": "^TNX",
     "aliases": ["TMV"]},
    {"symbol": "PFIX", "display": "Simplify Interest Rate Hedge ETF (PFIX)",
     "short": "PFIX", "asset_class": "etf", "proxy_for": "^TNX",
     "aliases": ["PFIX"]},
    {"symbol": "FXY", "display": "Invesco Yen Trust (FXY)", "short": "FXY",
     "asset_class": "etf", "proxy_for": "JPY=X",
     "aliases": ["FXY"]},
    {"symbol": "DXJ", "display": "WisdomTree Japan Hedged Equity (DXJ)",
     "short": "DXJ", "asset_class": "etf",
     "aliases": ["DXJ"]},
    {"symbol": "EWJ", "display": "iShares MSCI Japan ETF", "short": "EWJ",
     "asset_class": "etf", "aliases": ["EWJ", "Japan ETF"]},
    {"symbol": "EWU", "display": "iShares MSCI United Kingdom ETF",
     "short": "EWU", "asset_class": "etf", "aliases": ["EWU", "UK ETF"]},
    {"symbol": "DFEN", "display": "Direxion Daily Aerospace & Defense Bull 3X",
     "short": "DFEN", "asset_class": "etf", "aliases": ["DFEN"]},
    {"symbol": "GDX", "display": "VanEck Gold Miners ETF", "short": "GDX",
     "asset_class": "etf", "aliases": ["GDX", "Gold Miners ETF"]},
    {"symbol": "URA", "display": "Global X Uranium ETF", "short": "URA",
     "asset_class": "etf", "aliases": ["URA", "Uranium ETF"]},
    {"symbol": "XLE", "display": "Energy Select Sector SPDR (XLE)",
     "short": "XLE", "asset_class": "etf", "aliases": ["XLE", "Energy ETF"]},
    {"symbol": "SMH", "display": "VanEck Semiconductor ETF", "short": "SMH",
     "asset_class": "etf", "aliases": ["SMH", "Semiconductor ETF"]},
    # Spot Bitcoin ETFs
    {"symbol": "IBIT", "display": "iShares Bitcoin Trust (IBIT)", "short": "IBIT",
     "asset_class": "etf", "proxy_for": "BTC-USD", "aliases": ["IBIT"]},
    {"symbol": "FBTC", "display": "Fidelity Wise Origin Bitcoin Fund (FBTC)",
     "short": "FBTC", "asset_class": "etf", "proxy_for": "BTC-USD",
     "aliases": ["FBTC"]},
    {"symbol": "ARKB", "display": "ARK 21Shares Bitcoin ETF (ARKB)",
     "short": "ARKB", "asset_class": "etf", "proxy_for": "BTC-USD",
     "aliases": ["ARKB"]},
    {"symbol": "GBTC", "display": "Grayscale Bitcoin Trust (GBTC)",
     "short": "GBTC", "asset_class": "etf", "proxy_for": "BTC-USD",
     "aliases": ["GBTC"]},

    # ── US equities ───────────────────────────────────────────────────────
    {"symbol": "AAPL", "display": "Apple", "short": "Apple",
     "asset_class": "equity", "aliases": ["Apple", "Apple Inc"]},
    {"symbol": "AMD", "display": "Advanced Micro Devices", "short": "AMD",
     "asset_class": "equity", "aliases": ["AMD", "Advanced Micro Devices"]},
    {"symbol": "AMZN", "display": "Amazon", "short": "Amazon",
     "asset_class": "equity", "aliases": ["Amazon", "Amazon.com"]},
    {"symbol": "ARM", "display": "Arm Holdings", "short": "Arm",
     "asset_class": "equity", "aliases": ["Arm", "Arm Holdings"]},
    {"symbol": "AVGO", "display": "Broadcom", "short": "Broadcom",
     "asset_class": "equity", "aliases": ["Broadcom"]},
    {"symbol": "BSX", "display": "Boston Scientific", "short": "Boston Scientific",
     "asset_class": "equity", "aliases": ["Boston Scientific"]},
    {"symbol": "CAVA", "display": "Cava Group", "short": "Cava",
     "asset_class": "equity", "aliases": ["Cava", "Cava Group"]},
    {"symbol": "CCJ", "display": "Cameco", "short": "Cameco",
     "asset_class": "equity", "aliases": ["Cameco"]},
    {"symbol": "CEG", "display": "Constellation Energy", "short": "Constellation",
     "asset_class": "equity", "aliases": ["Constellation Energy"]},
    {"symbol": "CRM", "display": "Salesforce", "short": "Salesforce",
     "asset_class": "equity", "aliases": ["Salesforce"]},
    {"symbol": "CSCO", "display": "Cisco", "short": "Cisco",
     "asset_class": "equity", "aliases": ["Cisco", "Cisco Systems"]},
    {"symbol": "DE", "display": "Deere & Company", "short": "Deere",
     "asset_class": "equity", "aliases": ["Deere", "John Deere"]},
    {"symbol": "DELL", "display": "Dell Technologies", "short": "Dell",
     "asset_class": "equity", "aliases": ["Dell", "Dell Technologies"]},
    {"symbol": "DIS", "display": "Walt Disney", "short": "Disney",
     "asset_class": "equity", "aliases": ["Disney", "Walt Disney"]},
    {"symbol": "DJT", "display": "Trump Media & Technology Group",
     "short": "Trump Media", "asset_class": "equity",
     "aliases": ["Trump Media", "TMTG"]},
    {"symbol": "EBAY", "display": "eBay", "short": "eBay",
     "asset_class": "equity", "aliases": ["eBay"]},
    {"symbol": "EMR", "display": "Emerson Electric", "short": "Emerson",
     "asset_class": "equity", "aliases": ["Emerson", "Emerson Electric"]},
    {"symbol": "ESLT", "display": "Elbit Systems", "short": "Elbit",
     "asset_class": "equity", "aliases": ["Elbit", "Elbit Systems"]},
    {"symbol": "F", "display": "Ford Motor", "short": "Ford",
     "asset_class": "equity", "aliases": ["Ford", "Ford Motor"]},
    {"symbol": "GEV", "display": "GE Vernova", "short": "GE Vernova",
     "asset_class": "equity", "aliases": ["GE Vernova", "Vernova"]},
    {"symbol": "GM", "display": "General Motors", "short": "GM",
     "asset_class": "equity", "aliases": ["General Motors", "GM"]},
    {"symbol": "GOOGL", "display": "Alphabet (Class A)", "short": "Alphabet",
     "asset_class": "equity", "aliases": ["Alphabet", "Google"]},
    {"symbol": "GOOG", "display": "Alphabet (Class C)", "short": "Alphabet",
     "asset_class": "equity", "aliases": ["Alphabet Class C"],
     "canonical_symbol": "GOOGL"},
    {"symbol": "HIMS", "display": "Hims & Hers Health", "short": "Hims",
     "asset_class": "equity", "aliases": ["Hims", "Hims & Hers"]},
    {"symbol": "HPE", "display": "Hewlett Packard Enterprise", "short": "HPE",
     "asset_class": "equity", "aliases": ["HPE", "Hewlett Packard Enterprise"]},
    {"symbol": "INTC", "display": "Intel", "short": "Intel",
     "asset_class": "equity", "aliases": ["Intel"]},
    {"symbol": "JBLU", "display": "JetBlue Airways", "short": "JetBlue",
     "asset_class": "equity", "aliases": ["JetBlue"]},
    {"symbol": "JG", "display": "Aurora Mobile", "short": "Aurora Mobile",
     "asset_class": "equity", "aliases": ["Aurora Mobile"]},
    {"symbol": "KO", "display": "Coca-Cola", "short": "Coca-Cola",
     "asset_class": "equity", "aliases": ["Coca-Cola", "Coke"]},
    {"symbol": "LGF-A", "display": "Lions Gate Entertainment (Class A)",
     "short": "Lions Gate", "asset_class": "equity",
     "aliases": ["Lions Gate", "Lionsgate"]},
    {"symbol": "LLY", "display": "Eli Lilly", "short": "Eli Lilly",
     "asset_class": "equity", "aliases": ["Eli Lilly", "Lilly"]},
    {"symbol": "LMT", "display": "Lockheed Martin", "short": "Lockheed",
     "asset_class": "equity", "aliases": ["Lockheed", "Lockheed Martin"]},
    {"symbol": "META", "display": "Meta Platforms", "short": "Meta",
     "asset_class": "equity", "aliases": ["Meta", "Facebook", "Meta Platforms"]},
    {"symbol": "MP", "display": "MP Materials", "short": "MP Materials",
     "asset_class": "equity", "aliases": ["MP Materials"]},
    {"symbol": "MSFT", "display": "Microsoft", "short": "Microsoft",
     "asset_class": "equity", "aliases": ["Microsoft"]},
    {"symbol": "MU", "display": "Micron Technology", "short": "Micron",
     "asset_class": "equity", "aliases": ["Micron", "Micron Technology"]},
    {"symbol": "NEM", "display": "Newmont", "short": "Newmont",
     "asset_class": "equity", "aliases": ["Newmont", "Newmont Mining"]},
    {"symbol": "NNE", "display": "Nano Nuclear Energy", "short": "Nano Nuclear",
     "asset_class": "equity", "aliases": ["Nano Nuclear", "NANO Nuclear Energy"]},
    {"symbol": "NOW", "display": "ServiceNow", "short": "ServiceNow",
     "asset_class": "equity", "aliases": ["ServiceNow"]},
    {"symbol": "NVDA", "display": "Nvidia", "short": "Nvidia",
     "asset_class": "equity", "aliases": ["Nvidia"]},
    {"symbol": "NVO", "display": "Novo Nordisk", "short": "Novo Nordisk",
     "asset_class": "equity", "aliases": ["Novo Nordisk", "Novo"]},
    {"symbol": "NYT", "display": "New York Times", "short": "NYT",
     "asset_class": "equity", "aliases": ["New York Times", "NYT"]},
    {"symbol": "ORCL", "display": "Oracle", "short": "Oracle",
     "asset_class": "equity", "aliases": ["Oracle"]},
    {"symbol": "OXY", "display": "Occidental Petroleum", "short": "Occidental",
     "asset_class": "equity", "aliases": ["Occidental", "Occidental Petroleum"]},
    {"symbol": "PEP", "display": "PepsiCo", "short": "Pepsi",
     "asset_class": "equity", "aliases": ["Pepsi", "PepsiCo"]},
    {"symbol": "PLTR", "display": "Palantir", "short": "Palantir",
     "asset_class": "equity", "aliases": ["Palantir"]},
    {"symbol": "ROK", "display": "Rockwell Automation", "short": "Rockwell",
     "asset_class": "equity", "aliases": ["Rockwell", "Rockwell Automation"]},
    {"symbol": "SAVE", "display": "Spirit Airlines", "short": "Spirit",
     "asset_class": "equity", "aliases": ["Spirit Airlines"]},
    {"symbol": "SMCI", "display": "Super Micro Computer", "short": "Super Micro",
     "asset_class": "equity", "aliases": ["Super Micro", "Supermicro"]},
    {"symbol": "TEAM", "display": "Atlassian", "short": "Atlassian",
     "asset_class": "equity", "aliases": ["Atlassian"]},
    {"symbol": "TSLA", "display": "Tesla", "short": "Tesla",
     "asset_class": "equity", "aliases": ["Tesla"]},
    {"symbol": "TSM", "display": "Taiwan Semiconductor", "short": "TSMC",
     "asset_class": "equity", "aliases": ["TSMC", "Taiwan Semiconductor", "TSM"]},
    {"symbol": "TSCO", "display": "Tractor Supply Company", "short": "Tractor Supply",
     "asset_class": "equity", "aliases": ["TSCO", "Tractor Supply"]},
    {"symbol": "ULCC", "display": "Frontier Group Holdings", "short": "Frontier",
     "asset_class": "equity", "aliases": ["Frontier Airlines", "Frontier"]},
    {"symbol": "WBD", "display": "Warner Bros. Discovery", "short": "Warner Bros",
     "asset_class": "equity", "aliases": ["Warner Bros", "Warner Bros. Discovery"]},
    {"symbol": "XOM", "display": "ExxonMobil", "short": "Exxon",
     "asset_class": "equity", "aliases": ["Exxon", "ExxonMobil"]},

    # ── Additions from pending_instruments review (2026-05-05) ───────────
    {"symbol": "ADP", "display": "Automatic Data Processing", "short": "ADP",
     "asset_class": "equity", "aliases": ["ADP", "Automatic Data Processing"]},
    {"symbol": "AEM", "display": "Agnico Eagle Mines", "short": "Agnico Eagle",
     "asset_class": "equity", "aliases": ["Agnico Eagle", "Agnico Eagle Mines"]},
    {"symbol": "ALGT", "display": "Allegiant Travel", "short": "Allegiant",
     "asset_class": "equity", "aliases": ["Allegiant", "Allegiant Travel"]},
    {"symbol": "APD", "display": "Air Products and Chemicals", "short": "Air Products",
     "asset_class": "equity", "aliases": ["Air Products", "Air Products and Chemicals"]},
    {"symbol": "APLD", "display": "Applied Digital", "short": "Applied Digital",
     "asset_class": "equity", "aliases": ["Applied Digital"]},
    {"symbol": "ASO", "display": "Academy Sports and Outdoors", "short": "Academy",
     "asset_class": "equity",
     "aliases": ["Academy Sports", "Academy Sports + Outdoors", "Academy"]},
    {"symbol": "AVAV", "display": "AeroVironment", "short": "AeroVironment",
     "asset_class": "equity", "aliases": ["AeroVironment"]},
    {"symbol": "BA", "display": "Boeing", "short": "Boeing",
     "asset_class": "equity", "aliases": ["Boeing", "Boeing Company"]},
    {"symbol": "BR", "display": "Broadridge Financial Solutions", "short": "Broadridge",
     "asset_class": "equity", "aliases": ["Broadridge", "Broadridge Financial"]},
    {"symbol": "BRK-B", "display": "Berkshire Hathaway (Class B)", "short": "Berkshire",
     "asset_class": "equity",
     "aliases": ["Berkshire Hathaway", "Berkshire", "Berkshire B"]},
    {"symbol": "BW", "display": "Babcock & Wilcox Enterprises", "short": "Babcock & Wilcox",
     "asset_class": "equity", "aliases": ["Babcock & Wilcox", "Babcock and Wilcox"]},
    {"symbol": "CAG", "display": "Conagra Brands", "short": "Conagra",
     "asset_class": "equity", "aliases": ["Conagra", "Conagra Brands"]},
    {"symbol": "CCI", "display": "Crown Castle", "short": "Crown Castle",
     "asset_class": "equity", "aliases": ["Crown Castle"]},
    {"symbol": "CNI", "display": "Canadian National Railway", "short": "CN Rail",
     "asset_class": "equity",
     "aliases": ["Canadian National", "Canadian National Railway", "CN Rail", "CN"]},
    {"symbol": "CNR", "display": "Canadian National Railway (Toronto)", "short": "CN Rail",
     "asset_class": "equity", "tradable": 0,
     "aliases": ["Canadian National Toronto"], "canonical_symbol": "CNI"},
    {"symbol": "COIN", "display": "Coinbase Global", "short": "Coinbase",
     "asset_class": "equity", "aliases": ["Coinbase", "Coinbase Global"]},
    {"symbol": "COO", "display": "The Cooper Companies", "short": "Cooper",
     "asset_class": "equity", "aliases": ["Cooper Companies", "CooperCompanies"]},
    {"symbol": "CP", "display": "Canadian Pacific Kansas City", "short": "CPKC",
     "asset_class": "equity",
     "aliases": ["CPKC", "Canadian Pacific", "Canadian Pacific Kansas City"]},
    {"symbol": "CRSP", "display": "CRISPR Therapeutics", "short": "CRISPR",
     "asset_class": "equity", "aliases": ["CRISPR Therapeutics", "CRISPR"]},
    {"symbol": "CTRA", "display": "Coterra Energy", "short": "Coterra",
     "asset_class": "equity", "aliases": ["Coterra", "Coterra Energy"]},
    {"symbol": "CTSH", "display": "Cognizant Technology Solutions", "short": "Cognizant",
     "asset_class": "equity", "aliases": ["Cognizant", "Cognizant Technology"]},
    {"symbol": "CWH", "display": "Camping World Holdings", "short": "Camping World",
     "asset_class": "equity", "aliases": ["Camping World", "Camping World Holdings"]},
    {"symbol": "DNOW", "display": "DistributionNOW", "short": "DNOW",
     "asset_class": "equity", "aliases": ["DistributionNOW", "DNOW"]},
    {"symbol": "DUOL", "display": "Duolingo", "short": "Duolingo",
     "asset_class": "equity", "aliases": ["Duolingo"]},
    {"symbol": "DVN", "display": "Devon Energy", "short": "Devon",
     "asset_class": "equity", "aliases": ["Devon", "Devon Energy"]},
    {"symbol": "EFX", "display": "Equifax", "short": "Equifax",
     "asset_class": "equity", "aliases": ["Equifax"]},
    {"symbol": "EXOD", "display": "Exodus Movement", "short": "Exodus",
     "asset_class": "equity", "aliases": ["Exodus", "Exodus Movement"]},
    {"symbol": "EXPO", "display": "Exponent", "short": "Exponent",
     "asset_class": "equity", "aliases": ["Exponent"]},
    {"symbol": "FANG", "display": "Diamondback Energy", "short": "Diamondback",
     "asset_class": "equity", "aliases": ["Diamondback", "Diamondback Energy"]},
    {"symbol": "FHN", "display": "First Horizon", "short": "First Horizon",
     "asset_class": "equity", "aliases": ["First Horizon", "First Horizon Bank"]},
    {"symbol": "FIGR", "display": "Figure Technology Solutions", "short": "Figure",
     "asset_class": "equity", "aliases": ["Figure", "Figure Technology"]},
    {"symbol": "FMCC", "display": "Freddie Mac", "short": "Freddie Mac",
     "asset_class": "equity",
     "aliases": ["Freddie Mac", "Federal Home Loan Mortgage"]},
    {"symbol": "FN", "display": "Fabrinet", "short": "Fabrinet",
     "asset_class": "equity", "aliases": ["Fabrinet"]},
    {"symbol": "FRMI", "display": "Fermi", "short": "Fermi",
     "asset_class": "equity", "aliases": ["Fermi"]},
    {"symbol": "FTAI", "display": "FTAI Aviation", "short": "FTAI",
     "asset_class": "equity", "aliases": ["FTAI", "FTAI Aviation"]},
    {"symbol": "GIB", "display": "CGI Inc.", "short": "CGI",
     "asset_class": "equity", "aliases": ["CGI", "CGI Inc"]},
    {"symbol": "GIB.A", "display": "CGI Inc. (Toronto)", "short": "CGI",
     "asset_class": "equity", "tradable": 0,
     "aliases": ["CGI Toronto"], "canonical_symbol": "GIB"},
    {"symbol": "GME", "display": "GameStop", "short": "GameStop",
     "asset_class": "equity", "aliases": ["GameStop", "GME"]},
    {"symbol": "HR", "display": "Healthcare Realty Trust", "short": "Healthcare Realty",
     "asset_class": "equity",
     "aliases": ["Healthcare Realty", "Healthcare Realty Trust"]},
    {"symbol": "HRB", "display": "H&R Block", "short": "H&R Block",
     "asset_class": "equity", "aliases": ["H&R Block", "HR Block"]},
    {"symbol": "HRL", "display": "Hormel Foods", "short": "Hormel",
     "asset_class": "equity", "aliases": ["Hormel", "Hormel Foods"]},
    {"symbol": "IAC", "display": "IAC Inc.", "short": "IAC",
     "asset_class": "equity", "aliases": ["IAC", "IAC Inc"]},
    {"symbol": "IBM", "display": "International Business Machines", "short": "IBM",
     "asset_class": "equity", "aliases": ["IBM", "International Business Machines"]},
    {"symbol": "IESC", "display": "IES Holdings", "short": "IES Holdings",
     "asset_class": "equity", "aliases": ["IES Holdings", "IES"]},
    {"symbol": "INSP", "display": "Inspire Medical Systems", "short": "Inspire Medical",
     "asset_class": "equity",
     "aliases": ["Inspire Medical", "Inspire Medical Systems"]},
    {"symbol": "IREN", "display": "IREN", "short": "IREN",
     "asset_class": "equity", "aliases": ["IREN", "Iris Energy"]},
    {"symbol": "KBR", "display": "KBR Inc.", "short": "KBR",
     "asset_class": "equity", "aliases": ["KBR"]},
    {"symbol": "KR", "display": "Kroger", "short": "Kroger",
     "asset_class": "equity", "aliases": ["Kroger"]},
    {"symbol": "KTOS", "display": "Kratos Defense & Security Solutions",
     "short": "Kratos", "asset_class": "equity",
     "aliases": ["Kratos", "Kratos Defense"]},
    {"symbol": "LUV", "display": "Southwest Airlines", "short": "Southwest",
     "asset_class": "equity", "aliases": ["Southwest", "Southwest Airlines"]},
    {"symbol": "MGA", "display": "Magna International", "short": "Magna",
     "asset_class": "equity", "aliases": ["Magna", "Magna International"]},
    {"symbol": "MG", "display": "Magna International (Toronto)", "short": "Magna",
     "asset_class": "equity", "tradable": 0,
     "aliases": ["Magna Toronto"], "canonical_symbol": "MGA"},
    {"symbol": "MHK", "display": "Mohawk Industries", "short": "Mohawk",
     "asset_class": "equity", "aliases": ["Mohawk", "Mohawk Industries"]},
    {"symbol": "MNDY", "display": "monday.com", "short": "Monday.com",
     "asset_class": "equity", "aliases": ["monday.com", "Monday.com", "Monday"]},
    {"symbol": "MSTR", "display": "Strategy (formerly MicroStrategy)",
     "short": "Strategy",
     "asset_class": "equity", "aliases": ["MicroStrategy"]},
    {"symbol": "MUX", "display": "McEwen Mining", "short": "McEwen",
     "asset_class": "equity", "aliases": ["McEwen", "McEwen Mining", "McEwen Inc"]},
    {"symbol": "NCLH", "display": "Norwegian Cruise Line Holdings",
     "short": "Norwegian Cruise", "asset_class": "equity",
     "aliases": ["Norwegian Cruise", "Norwegian Cruise Line"]},
    {"symbol": "NHI", "display": "National Health Investors", "short": "NHI",
     "asset_class": "equity", "aliases": ["National Health Investors", "NHI"]},
    {"symbol": "NNN", "display": "NNN REIT", "short": "NNN REIT",
     "asset_class": "equity",
     "aliases": ["NNN REIT", "National Retail Properties"]},
    {"symbol": "NOC", "display": "Northrop Grumman", "short": "Northrop Grumman",
     "asset_class": "equity", "aliases": ["Northrop Grumman", "Northrop"]},
    {"symbol": "ODD", "display": "Oddity Tech", "short": "Oddity",
     "asset_class": "equity", "aliases": ["Oddity", "Oddity Tech"]},
    {"symbol": "ON", "display": "ON Semiconductor (onsemi)", "short": "onsemi",
     "asset_class": "equity", "aliases": ["onsemi", "ON Semiconductor"]},
    {"symbol": "PANW", "display": "Palo Alto Networks", "short": "Palo Alto",
     "asset_class": "equity", "aliases": ["Palo Alto Networks", "Palo Alto"]},
    {"symbol": "PII", "display": "Polaris Inc.", "short": "Polaris",
     "asset_class": "equity", "aliases": ["Polaris"]},
    {"symbol": "PINS", "display": "Pinterest", "short": "Pinterest",
     "asset_class": "equity", "aliases": ["Pinterest"]},
    {"symbol": "PLAY", "display": "Dave & Buster's Entertainment",
     "short": "Dave & Buster's", "asset_class": "equity",
     "aliases": ["Dave & Buster's", "Dave and Buster's"]},
    {"symbol": "POWL", "display": "Powell Industries", "short": "Powell",
     "asset_class": "equity", "aliases": ["Powell Industries"]},
    {"symbol": "PSKY", "display": "Paramount Skydance", "short": "Paramount",
     "asset_class": "equity", "aliases": ["Paramount", "Paramount Skydance"]},
    {"symbol": "PSN", "display": "Parsons Corporation", "short": "Parsons",
     "asset_class": "equity", "aliases": ["Parsons", "Parsons Corporation"]},
    {"symbol": "RCAT", "display": "Red Cat Holdings", "short": "Red Cat",
     "asset_class": "equity", "aliases": ["Red Cat", "Red Cat Holdings"]},
    {"symbol": "RIG", "display": "Transocean", "short": "Transocean",
     "asset_class": "equity", "aliases": ["Transocean"]},
    {"symbol": "SF", "display": "Stifel Financial", "short": "Stifel",
     "asset_class": "equity", "aliases": ["Stifel", "Stifel Financial"]},
    {"symbol": "STZ", "display": "Constellation Brands", "short": "Constellation Brands",
     "asset_class": "equity", "aliases": ["Constellation Brands"]},
    {"symbol": "TCOM", "display": "Trip.com Group", "short": "Trip.com",
     "asset_class": "equity", "aliases": ["Trip.com", "Trip.com Group"]},
    {"symbol": "TD", "display": "Toronto-Dominion Bank", "short": "TD Bank",
     "asset_class": "equity", "aliases": ["TD Bank", "Toronto-Dominion", "TD"]},
    {"symbol": "TGT", "display": "Target", "short": "Target",
     "asset_class": "equity", "aliases": ["Target"]},
    {"symbol": "TLX", "display": "Telix Pharmaceuticals", "short": "Telix",
     "asset_class": "equity", "aliases": ["Telix", "Telix Pharmaceuticals"]},
    {"symbol": "TRI", "display": "Thomson Reuters", "short": "Thomson Reuters",
     "asset_class": "equity", "aliases": ["Thomson Reuters"]},
    {"symbol": "TSN", "display": "Tyson Foods", "short": "Tyson",
     "asset_class": "equity", "aliases": ["Tyson", "Tyson Foods"]},
    {"symbol": "UFPI", "display": "UFP Industries", "short": "UFP Industries",
     "asset_class": "equity", "aliases": ["UFP Industries"]},
    {"symbol": "V", "display": "Visa", "short": "Visa",
     "asset_class": "equity", "aliases": ["Visa"]},
    {"symbol": "VNO", "display": "Vornado Realty Trust", "short": "Vornado",
     "asset_class": "equity", "aliases": ["Vornado", "Vornado Realty"]},
    {"symbol": "VNOM", "display": "Viper Energy", "short": "Viper Energy",
     "asset_class": "equity", "aliases": ["Viper Energy"]},
    {"symbol": "VTRS", "display": "Viatris", "short": "Viatris",
     "asset_class": "equity", "aliases": ["Viatris"]},
    {"symbol": "WGO", "display": "Winnebago Industries", "short": "Winnebago",
     "asset_class": "equity", "aliases": ["Winnebago", "Winnebago Industries"]},
    {"symbol": "WULF", "display": "TeraWulf", "short": "TeraWulf",
     "asset_class": "equity", "aliases": ["TeraWulf"]},
    {"symbol": "WYNN", "display": "Wynn Resorts", "short": "Wynn",
     "asset_class": "equity", "aliases": ["Wynn", "Wynn Resorts"]},
    {"symbol": "XRAY", "display": "Dentsply Sirona", "short": "Dentsply",
     "asset_class": "equity", "aliases": ["Dentsply", "Dentsply Sirona"]},

    # ── 2026-05-20 backlog pass (firehose seen_count ≥ 5) ─────────────────
    {"symbol": "ADI", "display": "Analog Devices", "short": "Analog Devices",
     "asset_class": "equity", "aliases": ["Analog Devices"]},
    {"symbol": "ALIT", "display": "Alight", "short": "Alight",
     "asset_class": "equity", "aliases": ["Alight"]},
    {"symbol": "APO", "display": "Apollo Global Management", "short": "Apollo",
     "asset_class": "equity", "aliases": ["Apollo Global Management"]},
    {"symbol": "BAC", "display": "Bank of America", "short": "Bank of America",
     "asset_class": "equity", "aliases": ["Bank of America"]},
    {"symbol": "BCE", "display": "BCE Inc.", "short": "BCE",
     "asset_class": "equity", "aliases": ["BCE Inc"]},
    {"symbol": "BIDU", "display": "Baidu", "short": "Baidu",
     "asset_class": "equity", "aliases": ["Baidu"]},
    {"symbol": "BX", "display": "Blackstone", "short": "Blackstone",
     "asset_class": "equity", "aliases": ["Blackstone Inc", "Blackstone Group"]},
    {"symbol": "CCL", "display": "Carnival Corporation", "short": "Carnival",
     "asset_class": "equity", "aliases": ["Carnival Corporation", "Carnival Cruise"]},
    {"symbol": "COTY", "display": "Coty Inc.", "short": "Coty",
     "asset_class": "equity", "aliases": ["Coty Inc"]},
    {"symbol": "CRWD", "display": "CrowdStrike", "short": "CrowdStrike",
     "asset_class": "equity", "aliases": ["CrowdStrike"]},
    {"symbol": "DOCU", "display": "DocuSign", "short": "DocuSign",
     "asset_class": "equity", "aliases": ["DocuSign"]},
    {"symbol": "EQNR", "display": "Equinor", "short": "Equinor",
     "asset_class": "equity", "aliases": ["Equinor"]},
    {"symbol": "FSK", "display": "FS KKR Capital", "short": "FS KKR",
     "asset_class": "equity", "aliases": ["FS KKR Capital", "FS KKR"]},
    {"symbol": "GLOB", "display": "Globant", "short": "Globant",
     "asset_class": "equity", "aliases": ["Globant"]},
    {"symbol": "GPK", "display": "Graphic Packaging", "short": "Graphic Packaging",
     "asset_class": "equity", "aliases": ["Graphic Packaging"]},
    {"symbol": "GS", "display": "Goldman Sachs", "short": "Goldman Sachs",
     "asset_class": "equity", "aliases": ["Goldman Sachs"]},
    {"symbol": "HD", "display": "Home Depot", "short": "Home Depot",
     "asset_class": "equity", "aliases": ["Home Depot", "The Home Depot"]},
    {"symbol": "HII", "display": "Huntington Ingalls Industries", "short": "Huntington Ingalls",
     "asset_class": "equity", "aliases": ["Huntington Ingalls"]},
    {"symbol": "HTGC", "display": "Hercules Capital", "short": "Hercules Capital",
     "asset_class": "equity", "aliases": ["Hercules Capital"]},
    {"symbol": "IBRX", "display": "ImmunityBio", "short": "ImmunityBio",
     "asset_class": "equity", "aliases": ["ImmunityBio"]},
    {"symbol": "INGR", "display": "Ingredion", "short": "Ingredion",
     "asset_class": "equity", "aliases": ["Ingredion"]},
    {"symbol": "KBH", "display": "KB Home", "short": "KB Home",
     "asset_class": "equity", "aliases": ["KB Home"]},
    {"symbol": "LOW", "display": "Lowe's Companies", "short": "Lowe's",
     "asset_class": "equity", "aliases": ["Lowe's", "Lowe's Companies"]},
    {"symbol": "MEDP", "display": "Medpace", "short": "Medpace",
     "asset_class": "equity", "aliases": ["Medpace"]},
    {"symbol": "RKLB", "display": "Rocket Lab", "short": "Rocket Lab",
     "asset_class": "equity", "aliases": ["Rocket Lab"]},
    {"symbol": "RTX", "display": "RTX Corporation", "short": "RTX",
     "asset_class": "equity", "aliases": ["RTX Corporation", "Raytheon Technologies", "Raytheon"]},
    {"symbol": "SAP", "display": "SAP SE", "short": "SAP",
     "asset_class": "equity", "aliases": ["SAP SE"]},
    {"symbol": "SLF", "display": "Sun Life Financial", "short": "Sun Life",
     "asset_class": "equity", "aliases": ["Sun Life Financial"]},
    {"symbol": "SPGI", "display": "S&P Global", "short": "S&P Global",
     "asset_class": "equity", "aliases": ["S&P Global"]},
    {"symbol": "STLA", "display": "Stellantis", "short": "Stellantis",
     "asset_class": "equity", "aliases": ["Stellantis"]},
    {"symbol": "TJX", "display": "TJX Companies", "short": "TJX",
     "asset_class": "equity", "aliases": ["TJX Companies"]},
    {"symbol": "UPST", "display": "Upstart Holdings", "short": "Upstart",
     "asset_class": "equity", "aliases": ["Upstart Holdings"]},
    {"symbol": "VEEV", "display": "Veeva Systems", "short": "Veeva",
     "asset_class": "equity", "aliases": ["Veeva Systems"]},
    {"symbol": "VZ", "display": "Verizon", "short": "Verizon",
     "asset_class": "equity", "aliases": ["Verizon"]},
    {"symbol": "WTW", "display": "Willis Towers Watson", "short": "WTW",
     "asset_class": "equity", "aliases": ["Willis Towers Watson"]},

    # ── 2026-05-25 pending-instruments approvals ─────────────────────────
    {"symbol": "ALAB", "display": "Astera Labs", "short": "Astera Labs",
     "asset_class": "equity", "aliases": ["Astera Labs"]},
    {"symbol": "AMAT", "display": "Applied Materials", "short": "Applied Materials",
     "asset_class": "equity", "aliases": ["Applied Materials"]},
    {"symbol": "BABA", "display": "Alibaba Group", "short": "Alibaba",
     "asset_class": "equity", "aliases": ["Alibaba", "Alibaba Group"]},
    {"symbol": "BIIB", "display": "Biogen", "short": "Biogen",
     "asset_class": "equity", "aliases": ["Biogen"]},
    {"symbol": "CAT", "display": "Caterpillar", "short": "Caterpillar",
     "asset_class": "equity", "aliases": ["Caterpillar"]},
    {"symbol": "CLSK", "display": "CleanSpark", "short": "CleanSpark",
     "asset_class": "equity", "aliases": ["CleanSpark"]},
    {"symbol": "CRWV", "display": "CoreWeave", "short": "CoreWeave",
     "asset_class": "equity", "aliases": ["CoreWeave"]},
    {"symbol": "CVS", "display": "CVS Health", "short": "CVS Health",
     "asset_class": "equity", "aliases": ["CVS Health"]},
    {"symbol": "ENPH", "display": "Enphase Energy", "short": "Enphase",
     "asset_class": "equity", "aliases": ["Enphase", "Enphase Energy"]},
    {"symbol": "GFS", "display": "GlobalFoundries", "short": "GlobalFoundries",
     "asset_class": "equity", "aliases": ["GlobalFoundries"]},
    {"symbol": "HOOD", "display": "Robinhood Markets", "short": "Robinhood",
     "asset_class": "equity", "aliases": ["Robinhood", "Robinhood Markets"]},
    {"symbol": "INTU", "display": "Intuit", "short": "Intuit",
     "asset_class": "equity", "aliases": ["Intuit"]},
    {"symbol": "KEYS", "display": "Keysight Technologies", "short": "Keysight",
     "asset_class": "equity", "aliases": ["Keysight", "Keysight Technologies"]},
    {"symbol": "MDB", "display": "MongoDB", "short": "MongoDB",
     "asset_class": "equity", "aliases": ["MongoDB"]},
    {"symbol": "MRVL", "display": "Marvell Technology", "short": "Marvell",
     "asset_class": "equity", "aliases": ["Marvell", "Marvell Technology"]},
    {"symbol": "NEE", "display": "NextEra Energy", "short": "NextEra",
     "asset_class": "equity", "aliases": ["NextEra", "NextEra Energy"]},
    {"symbol": "NFLX", "display": "Netflix", "short": "Netflix",
     "asset_class": "equity", "aliases": ["Netflix"]},
    {"symbol": "NIO", "display": "NIO", "short": "NIO",
     "asset_class": "equity", "aliases": ["NIO Inc", "Nio"]},
    {"symbol": "PLUG", "display": "Plug Power", "short": "Plug Power",
     "asset_class": "equity", "aliases": ["Plug Power"]},
    {"symbol": "QBTS", "display": "D-Wave Quantum", "short": "D-Wave",
     "asset_class": "equity", "aliases": ["D-Wave", "D-Wave Quantum"]},
    {"symbol": "QUBT", "display": "Quantum Computing Inc.", "short": "Quantum Computing",
     "asset_class": "equity", "aliases": ["Quantum Computing Inc"]},
    {"symbol": "ROST", "display": "Ross Stores", "short": "Ross Stores",
     "asset_class": "equity", "aliases": ["Ross Stores"]},
    {"symbol": "SNDK", "display": "SanDisk", "short": "SanDisk",
     "asset_class": "equity", "aliases": ["SanDisk"]},
    {"symbol": "SNOW", "display": "Snowflake", "short": "Snowflake",
     "asset_class": "equity", "aliases": ["Snowflake"]},
    {"symbol": "SPOT", "display": "Spotify Technology", "short": "Spotify",
     "asset_class": "equity", "aliases": ["Spotify", "Spotify Technology"]},
    {"symbol": "TOL", "display": "Toll Brothers", "short": "Toll Brothers",
     "asset_class": "equity", "aliases": ["Toll Brothers"]},
    {"symbol": "TTWO", "display": "Take-Two Interactive", "short": "Take-Two",
     "asset_class": "equity", "aliases": ["Take-Two", "Take-Two Interactive"]},
    {"symbol": "VRT", "display": "Vertiv Holdings", "short": "Vertiv",
     "asset_class": "equity", "aliases": ["Vertiv", "Vertiv Holdings"]},
    {"symbol": "WDAY", "display": "Workday", "short": "Workday",
     "asset_class": "equity", "aliases": ["Workday"]},
    {"symbol": "WIX", "display": "Wix.com", "short": "Wix",
     "asset_class": "equity", "aliases": ["Wix.com"]},
    {"symbol": "WMT", "display": "Walmart", "short": "Walmart",
     "asset_class": "equity", "aliases": ["Walmart"]},

    # ── ADRs / foreign listings ───────────────────────────────────────────
    {"symbol": "FANUY", "display": "Fanuc (ADR)", "short": "Fanuc",
     "asset_class": "equity", "aliases": ["Fanuc"]},
    {"symbol": "NTDOY", "display": "Nintendo (ADR)", "short": "Nintendo",
     "asset_class": "equity", "aliases": ["Nintendo"]},
    {"symbol": "SONY", "display": "Sony Group (ADR)", "short": "Sony",
     "asset_class": "equity", "aliases": ["Sony"]},
    {"symbol": "SQNXF", "display": "Square Enix (OTC ADR)", "short": "Square Enix",
     "asset_class": "equity", "aliases": ["Square Enix"]},
    {"symbol": "SSNLF", "display": "Samsung Electronics (OTC ADR)",
     "short": "Samsung", "asset_class": "equity",
     "aliases": ["Samsung", "Samsung Electronics"]},
    {"symbol": "005930.KS", "display": "Samsung Electronics (Korea)",
     "short": "Samsung", "asset_class": "equity",
     "aliases": ["Samsung Electronics Korea"]},
    {"symbol": "9684.T", "display": "Square Enix (Tokyo)",
     "short": "Square Enix", "asset_class": "equity",
     "aliases": ["Square Enix Tokyo"]},
    {"symbol": "BA.L", "display": "BAE Systems (London)", "short": "BAE",
     "asset_class": "equity", "aliases": ["BAE", "BAE Systems"]},
    {"symbol": "RHM.DE", "display": "Rheinmetall (Frankfurt)",
     "short": "Rheinmetall", "asset_class": "equity",
     "aliases": ["Rheinmetall"]},
    {"symbol": "PHOR.ME", "display": "PhosAgro (Moscow)", "short": "PhosAgro",
     "asset_class": "equity", "tradable": 0,
     "aliases": ["PhosAgro"]},
    {"symbol": "600346.SS", "display": "Hengli Petrochemical (Shanghai)",
     "short": "Hengli", "asset_class": "equity",
     "aliases": ["Hengli Petrochemical"]},
    {"symbol": "HLAG.DE", "display": "Hapag-Lloyd (Frankfurt)",
     "short": "Hapag-Lloyd", "asset_class": "equity",
     "aliases": ["Hapag-Lloyd", "Hapag Lloyd"]},
    {"symbol": "LYSDY", "display": "Lynas Rare Earths (OTC ADR)", "short": "Lynas",
     "asset_class": "equity", "aliases": ["Lynas", "Lynas Rare Earths"]},

    # ── Crypto (Yahoo `-USD` form) ────────────────────────────────────────
    {"symbol": "BTC-USD", "display": "Bitcoin", "short": "BTC",
     "asset_class": "crypto",
     "aliases": ["BTC", "Bitcoin"],
     "alpaca_symbol": "BTC/USD", "fmp_symbol": "BTCUSD"},
    {"symbol": "BTC", "display": "Bitcoin", "short": "BTC",
     "asset_class": "crypto",
     "aliases": ["BTC", "Bitcoin"],
     "alpaca_symbol": "BTC/USD", "fmp_symbol": "BTCUSD",
     "canonical_symbol": "BTC-USD"},
    {"symbol": "ETH-USD", "display": "Ethereum", "short": "ETH",
     "asset_class": "crypto",
     "aliases": ["ETH", "Ethereum", "Ether"],
     "alpaca_symbol": "ETH/USD", "fmp_symbol": "ETHUSD"},
    {"symbol": "AAVE-USD", "display": "Aave", "short": "AAVE",
     "asset_class": "crypto",
     "aliases": ["AAVE", "Aave"],
     "alpaca_symbol": "AAVE/USD", "fmp_symbol": "AAVEUSD"},
    {"symbol": "LDO-USD", "display": "Lido DAO", "short": "LDO",
     "asset_class": "crypto",
     "aliases": ["LDO", "Lido"]},
    {"symbol": "MNT-USD", "display": "Mantle", "short": "MNT",
     "asset_class": "crypto",
     "aliases": ["MNT", "Mantle"]},
    {"symbol": "USDT", "display": "Tether (USDT)", "short": "USDT",
     "asset_class": "crypto",
     "aliases": ["USDT", "Tether"],
     "alpaca_symbol": "USDT/USD", "fmp_symbol": "USDTUSD"},
    {"symbol": "TRX", "display": "TRON", "short": "TRX",
     "asset_class": "crypto",
     "aliases": ["TRX", "TRON", "Tron"],
     "alpaca_symbol": "TRX/USD", "fmp_symbol": "TRXUSD"},
]


def _row_tuple(entry: dict[str, Any]) -> tuple[Any, ...]:
    """Map a seed dict to the column tuple expected by the INSERT."""
    return (
        entry["symbol"],
        entry["display"],
        entry["short"],
        entry["asset_class"],
        json.dumps(entry.get("aliases", []), ensure_ascii=False),
        entry.get("canonical_symbol"),
        entry.get("alpaca_symbol"),
        entry.get("fmp_symbol"),
        int(entry.get("tradable", 1)),
        entry.get("proxy_for"),
        int(entry.get("active", 1)),
    )


def seed(db_path: Path = DB_PATH) -> int:
    """Idempotently upsert every entry in INSTRUMENTS. Returns row count."""
    if not db_path.exists():
        raise FileNotFoundError(f"DB not found at {db_path}; run `db.schema` first.")

    seen = {e["symbol"] for e in INSTRUMENTS}
    if len(seen) != len(INSTRUMENTS):
        raise ValueError("duplicate symbol(s) in INSTRUMENTS seed")

    conn = sqlite3.connect(db_path)
    try:
        with conn:
            conn.executemany(
                """
                INSERT INTO instruments (
                    symbol, display, short, asset_class, aliases_json,
                    canonical_symbol, alpaca_symbol, fmp_symbol, tradable,
                    proxy_for, active, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ','now'))
                ON CONFLICT(symbol) DO UPDATE SET
                    display=excluded.display,
                    short=excluded.short,
                    asset_class=excluded.asset_class,
                    aliases_json=excluded.aliases_json,
                    canonical_symbol=excluded.canonical_symbol,
                    alpaca_symbol=excluded.alpaca_symbol,
                    fmp_symbol=excluded.fmp_symbol,
                    tradable=excluded.tradable,
                    proxy_for=excluded.proxy_for,
                    active=excluded.active,
                    updated_at=strftime('%Y-%m-%dT%H:%M:%SZ','now')
                """,
                [_row_tuple(e) for e in INSTRUMENTS],
            )
    finally:
        conn.close()
    return len(INSTRUMENTS)


def audit_unmapped(db_path: Path = DB_PATH) -> list[str]:
    """Return symbols present in entity_tickers but missing from instruments."""
    conn = sqlite3.connect(db_path)
    try:
        rows = conn.execute(
            "SELECT DISTINCT symbol FROM entity_tickers "
            "WHERE symbol NOT IN (SELECT symbol FROM instruments) "
            "ORDER BY symbol"
        ).fetchall()
    finally:
        conn.close()
    return [r[0] for r in rows]


if __name__ == "__main__":
    n = seed()
    print(f"Seeded {n} instruments.")
    missing = audit_unmapped()
    if missing:
        print(f"WARNING: {len(missing)} symbol(s) in entity_tickers have no registry row:")
        for sym in missing:
            print(f"  - {sym}")
    else:
        print("All entity_tickers symbols are mapped.")
